services:
  db:
    image: mariadb:10.11
    container_name: ${PROJECT_NAME}-db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress

  wordpress:
    image: dunglas/frankenphp:latest
    container_name: ${PROJECT_NAME}-app
    restart: always
    depends_on:
      - db
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./html:/var/www/html
      - ./init-wp.sh:/usr/local/bin/init-wp.sh
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/conf.d"
      PHP_OPTIONS: "-d memory_limit=512M -d upload_max_filesize=100M -d post_max_size=100M"
    entrypoint: ["sh", "-c", "init-wp.sh && frankenphp run --config /etc/caddy/Caddyfile"]

  pma:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}-pma
    environment:
      PMA_HOST: db 
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: https://dev.${PROJECT_NAME}.theo-manya.fr/pma/ # <--- AJOUTE ÇA
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - db

volumes:
  db_data: {}